using System;
using System.Threading.Tasks;
using Discord;
using Discord.Interactions;
using FischBot.Services.ArtificialIntelligenceService;
using FischBot.Services.DiscordModuleService;

namespace FischBot.Modules
{
    [Group("ai", "Artificial intelligence commands")]
    public class ArtificialIntelligenceModule : FischBotInteractionModuleBase<SocketInteractionContext>
    {
        private readonly IArtificialIntelligenceService _artificialIntelligenceService;

        public ArtificialIntelligenceModule(IDiscordModuleService moduleService, IArtificialIntelligenceService artificialIntelligenceService) : base(moduleService)
        {
            _artificialIntelligenceService = artificialIntelligenceService;
        }

        [SlashCommand("imagefromtext", "Displays AI-generated image from text")]
        public async Task DisplayImageFromText([Summary(description: "text to generate an image from")] string text) 
        {
            await RespondAsync("Your image is being generated, this may take a moment.");

            try
            {
                var fileName = "output.jpg";
                var imageFromText = await _artificialIntelligenceService.GetImageFromText(text);

                var imageEmbed = new EmbedBuilder()
                    .WithTitle(text)
                    .WithImageUrl($"attachment://{fileName}")
                    .WithFooter("Generated by DeepAI image2text API")
                    .Build();

                await FollowupWithFileAsync(fileStream: imageFromText.ImageStream, fileName: fileName, embed: imageEmbed);
            }
            catch (Exception)
            {
                await FollowupAsync("I'm sorry, something went wrong while I was generating this image :(");
            }
        }
    }
}
